#!/usr/bin/env python3
"""Write the GOVERNANCE.md pointer for a repository, from the registry.

A repository whose only constitution is a superseded one will be read, in full,
by the next agent that starts there. The document being outdated is not the
problem -- nothing in that repository says so. This writes the file that says so.

The superseded document is never touched. `Dispatch/CLAUDE.md` section 7:
"Do not edit old decisions to hide their history. Mark them SUPERSEDED and cite
the ruling that replaced them." A pointer beside it is exactly that mark.

    python Governance/tools/write_pointers.py --repo Joe-Assistant --output GOVERNANCE.md
    python Governance/tools/write_pointers.py --all --output-dir Governance/pointers
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dispatch_governance.registry import (  # noqa: E402
    DEFAULT_REGISTRY,
    SUPERSEDED,
    load_registry,
)

TEMPLATE = """# GOVERNANCE — what actually governs {repo}

<!--
Generated by Governance/tools/write_pointers.py from GOVERNANCE_REGISTRY.json.
Regenerate rather than edit: the registry is the record, this file is a view of it.
-->

**Programme authority: `{authority_repo}/{authority_path}`.**

Read that first. It is the only governance in this programme whose clauses are
enforced by a test that fails a build (`Dispatch/tests/test_repository_doctrine.py`),
which is what makes it the authority rather than one more document with an
opinion.

## What is current here

{current_block}

## What is in this repository and does NOT govern

These files are still here on purpose. `Dispatch/CLAUDE.md` section 7 forbids
editing an old decision to hide its history — so they are kept, readable, and
marked, rather than deleted.

{superseded_block}

## The one that matters most

`DISPATCH_CONSTITUTION_v2` names a **Manager / Control** department and forbids
"bypassing Manager". `DISPATCH_CONSTITUTION_v3` describes Manager as the Run
Office function. **Neither authorises building one.**

`Dispatch/CLAUDE.md` §5.6: *"There is no Manager component in the current
architecture. Do not create, restore, reference, or infer a Manager component,
Manager agent, or Manager authority."* `Dispatch/docs/MANAGER.md` records why: it
was named in planning and never built. `Dispatch/tests/test_repository_doctrine.py`
enforces the ban with an allowlist of every permissible use of the word, so a
build that introduces one fails.

The constitutions describe an intended **organisational shape**. CLAUDE.md and
its tests govern what the **running program** may contain. They are not in
conflict once the question each answers is stated — and that statement is the
registry.

## Checking it yourself

```
python -m dispatch_governance show {repo}
python -m dispatch_governance answer "may a Manager component be built into Dispatch"
python -m dispatch_governance check <directory holding the clones>
```

Recorded {generated_at} from `Governance/GOVERNANCE_REGISTRY.json`.
"""


def render(registry, repo: str) -> str:
    authority = registry.get(registry.authority)
    binding = registry.binding_for(repo)
    stale = [d for d in registry.for_repo(repo) if d.status == SUPERSEDED]
    current_block = "\n".join(
        f"- **`{d.path}`** — {d.scope}" + (f"\n  <br>{d.note}" if d.note else "")
        for d in binding
    ) or "- Nothing in this repository is current programme governance."
    superseded_block = "\n".join(
        f"- **`{d.path}`** — superseded by `{d.superseded_by}`. {d.note}" for d in stale
    ) or "- Nothing."
    return TEMPLATE.format(
        repo=repo,
        authority_repo=authority.repo,
        authority_path=authority.path,
        current_block=current_block,
        superseded_block=superseded_block,
        generated_at=registry.generated_at,
    )


def repos_needing_a_pointer(registry) -> list[str]:
    return sorted({d.repo for d in registry.documents if d.status == SUPERSEDED})


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--repo")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--output-dir", type=Path)
    args = parser.parse_args(argv)

    registry = load_registry(args.registry)

    if args.all:
        target_dir = args.output_dir or Path("Governance/pointers")
        target_dir.mkdir(parents=True, exist_ok=True)
        for repo in repos_needing_a_pointer(registry):
            (target_dir / f"{repo}-GOVERNANCE.md").write_text(
                render(registry, repo), encoding="utf-8"
            )
            print(f"  {target_dir / f'{repo}-GOVERNANCE.md'}")
        return 0

    if not args.repo:
        parser.error("--repo is required unless --all is given")
    text = render(registry, args.repo)
    if args.output:
        args.output.write_text(text, encoding="utf-8")
        print(f"  {args.output}")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
